import {
  Alert,
  Break,
  CliChecksumTable,
  CodeBlock,
  CodeTabs,
  ConfigKey,
  DefinitionList,
  DocImage,
  Expandable,
  GuideGrid,
  JsBundleList,
  LambdaLayerDetail,
  LinkWithPlatformIcon,
  Note,
  OnboardingOption,
  OnboardingOptionButtons,
  OrgAuthTokenNote,
  PageGrid,
  ParamTable,
  PiiFields,
  PlatformCategorySection,
  PlatformGrid,
  PlatformIdentifier,
  PlatformLink,
  PlatformLinkWithLogo,
  PlatformOrGuideName,
  PlatformSdkPackageName,
  PlatformSection,
  RelayMetrics,
  SandboxLink,
  SignInNote,
  SmartLink,
  VimeoEmbed,
} from '@sentry/ui-shared';

export function mdxComponents(
  dynamicComponents: any = {},
  wrapper: any = ({children}) => children
) {
  return {
    Alert,
    Break,
    CliChecksumTable,
    CodeBlock,
    CodeTabs,
    ConfigKey,
    DefinitionList,
    Expandable,
    GuideGrid,
    JsBundleList,
    LambdaLayerDetail,
    Link: SmartLink,
    LinkWithPlatformIcon,
    Note,
    OrgAuthTokenNote,
    PageGrid,
    ParamTable,
    PiiFields,
    PlatformGrid,
    PlatformIdentifier,
    PlatformLink,
    PlatformLinkWithLogo,
    PlatformSection,
    PlatformCategorySection,
    PlatformOrGuideName,
    PlatformSdkPackageName,
    OnboardingOption,
    OnboardingOptionButtons,
    RelayMetrics,
    SandboxLink,
    SignInNote,
    VimeoEmbed,
    a: SmartLink,
    img: DocImage,
    ...dynamicComponents,
    wrapper,
  };
}
